# Docker Compose 配置文件，包含3大部分 version、services、networks
version: '3'
services:
  # 服务名称
  mysql:
    # 容器名称
    container_name: mysql
    # 镜像名称
    image: mysql:5.7
    # 暴露端口
    ports:
      - "3306:3306"
    # 设置卷挂载路径
    volumes:
      - ./data/volume/mysql:/opt/data
    # 环境变量
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: agan
      MYSQL_ROOT_PASSWORD: agan

    # 设置权限 ：拥有root权限
    privileged: true

    networks:
      - default

networks:
  default:
    external:
      name: jadennet