apiVersion: apps/v1beta1      #指定api的版本
kind: Deployment              #指定创建资源的类型 
metadata:                     #deployment的属性
  name: eureka-ha-2-deployment      #deployment的名字
spec:                         #deployment的规格说明
  replicas: 1                 #副本的数量，集群有多少个服务
  template:                   #定义pod的模板
    metadata:                 #pod的属性
      labels:                 #pod的标签
        app: eureka-ha-2            #pod的标签名字，这个很重要，它代表整个集群的标签
    spec:                     #pod的规格说明
      containers:             #pod的容器属性
        - name: eureka-ha-2-container    #容器名
          image: localhost:5000/eureka-server:0.0.2        #docker镜像
          ports:               #docker 的端口属性
            - containerPort: 31764 #docker的端口号
          env:
            - name: EUREKA_SERVICE_URL
              value: 'http://eureka-ha-1-service:31762/eureka/'
            - name: SERVERPORT
              value: '31764'